version: '2.0'

services:
  app:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://travel-ka:travel-ka@postgres/travel-ka
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=travel-ka
      - POSTGRES_PASSWORD=travel-ka
      - POSTGRES_DB=travel-ka

volumes:
  postgres_data:
    driver: local
